name: leetcode_foundations
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/heydufarias/leetcode-foundations

environment:
  sdk: ^3.11.1

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
